//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchatAgileNoSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anonyme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anonyme()
        {
            this.Message = new HashSet<Message>();
            this.SalonTchat = new HashSet<SalonTchat>();
        }
    
        public int id_anonyme { get; set; }
        public string pseudo_anonyme { get; set; }
        public bool isActif_anonyme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalonTchat> SalonTchat { get; set; }
    }
}
