//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchatAgileNoSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantsSalon
    {
        public int id_ps { get; set; }
        public int id_salon_ps { get; set; }
        public int id_user_ps { get; set; }
        public bool isUserAnonyme_ps { get; set; }
        public int id_salon { get; set; }
    
        public virtual SalonTchat SalonTchat { get; set; }
    }
}
