//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchatAgileNoSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TchatNoSQLEntities : DbContext
    {
        public TchatNoSQLEntities()
            : base("name=TchatNoSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anonyme> Anonyme { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<ParticipantsSalon> ParticipantsSalon { get; set; }
        public virtual DbSet<SalonTchat> SalonTchat { get; set; }
        public virtual DbSet<UserClassique> UserClassique { get; set; }
    }
}
