//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchatAgileNoSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFacebook
    {
        public int id_user { get; set; }
        public byte[] photoprofil_userfb { get; set; }
        public string email_user { get; set; }
        public bool isActif_user { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
