//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchatAgileNoSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserClassique
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserClassique()
        {
            this.Message = new HashSet<Message>();
            this.Contacts = new HashSet<Contacts>();
            this.SalonTchat = new HashSet<SalonTchat>();
        }
    
        public int id_usercl { get; set; }
        public string email_usercl { get; set; }
        public string pseudo_usercl { get; set; }
        public string password_usercl { get; set; }
        public string nom_usercl { get; set; }
        public string prenom_usercl { get; set; }
        public System.DateTime datenaissance_usercl { get; set; }
        public string pays_usercl { get; set; }
        public string langue_usercl { get; set; }
        public System.DateTime dateinscription_usercl { get; set; }
        public byte[] avatar_usercl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacts> Contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalonTchat> SalonTchat { get; set; }
    }
}
