//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchatAgileNoSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserClassique
    {
        public int id_user { get; set; }
        public string pseudo_usercl { get; set; }
        public string password_usercl { get; set; }
        public string nom_usercl { get; set; }
        public string prenom_usercl { get; set; }
        public System.DateTime datenaissance_usercl { get; set; }
        public string pays_usercl { get; set; }
        public string langue_usercl { get; set; }
        public System.DateTime dateinscription_usercl { get; set; }
        public byte[] avatar_usercl { get; set; }
        public string email_user { get; set; }
        public bool isActif_user { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
